language: ruby
rvm:
  - 2.0.0
  - 2.1
  - 2.2
sudo: false
cache: bundler
script:
  - "bundle exec rake $TASK"
gemfile:
  - Gemfile
  - spec/rails/Gemfile
env:
  - TASK=spec
  - TASK=rails:spec
  - TASK=bench TIME=20
matrix:
  allow_failures:
    - env: TASK=bench TIME=20
  exclude:
    - env: TASK=spec
      gemfile: spec/rails/Gemfile
    - env: TASK=rails:spec
      gemfile: Gemfile
    - env: TASK=bench TIME=20
      gemfile: spec/rails/Gemfile
    - rvm: 2.1
      env: TASK=rails:spec
    - rvm: 2.1
      env: TASK=bench TIME=20
    - rvm: 2.0.0
      env: TASK=rails:spec
    - rvm: 2.0.0
      env: TASK=bench TIME=20
